project:
  type: website
  resources:
    - "_static/"

website:
  title: "Mobile Robotics"
  page-footer: "Copyright 2024, Anthony J. Clark"
  # TODO: change to "MR" of "CS181R"
  favicon: images/Icon-favicon.png
  # logo-alt:
  search: true
  page-navigation: true
  repo-url: https://github.com/anthonyjclark/cs181r
  repo-actions: [edit, issue]
  reader-mode: true
  site-url: "https://cs.pomona.edu/classes/cs181r"

  navbar:
    # background: primary
    left:
      - text: Schedule
        file: pages/schedule.qmd
      - text: Book
        file: book/book.qmd

  sidebar:
    - title: "Book"
      style: "docked"
      logo: images/Logo.png
      contents:
        - book/book.qmd
        - section: "Unit 1: Design and Electronics"
          contents:
            - book/01-IntroductionAndDesign.qmd
            - book/02-LayoutAndPrototyping.qmd
            - book/03-SafetyAndElectronics.qmd
        - text: "---"
        - section: "Unit 2: Embedded Systems"
          contents:
            - book/04-ProgrammingWithToit.qmd
            - book/05-MicrocontrollerUtilities.qmd
            - book/06-OpenLoopGoToGoal.qmd
            - book/07-MotorControl.qmd
            - book/08-ClosedLoopGoToGoal.qmd
            - book/09-EmbeddedSystems.qmd
            - book/10-Arduino.qmd
            - book/11-ArduinoCodeRefactoring.qmd
            - book/12-ArduinoMotorControl.qmd
            - book/15-ArduinoCLI.qmd
        - text: "---"
        - section: "Unit 3: Modeling and Feedback Control"
          contents:
            - book/13-PoseEstimation.qmd
            - book/14-Kinematics.qmd
            - book/16-MotionControl.qmd
        - text: "---"
        - section: "Unit 4: Maps and Motion Planning"
          contents:
        - text: "---"
        - section: "Unit 5: Uncertainty and State Estimation"
          contents:
        - text: "---"
        - section: "Unit 6: Localization and Mapping"
          contents:
        - text: "---"
        - section: "Unit 7: Vision and Learning"
          contents:
        - text: "---"
        - section: "Unit 8: Societal Impacts"
          contents:
        - text: "---"
        - section: "Back Matter"
          contents:
            # - book/Glossary.qmd
            - book/A1-Notation.qmd
            - book/A2-Troubleshooting.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-in-header:
      text: <script src="https://hypothes.is/embed.js" async></script>
