project:
  type: website
  resources:
    - "_static/"

website:
  title: "Mobile Robotics"
  page-footer: "Copyright 2024, Anthony J. Clark"
  # TODO: change to "MR" of "CS181R"
  favicon: images/Icon-favicon.png
  # logo-alt:
  search: true
  page-navigation: true
  repo-url: https://github.com/anthonyjclark/cs181r
  repo-actions: [edit, issue]
  reader-mode: true
  site-url: "https://cs.pomona.edu/classes/cs181r"

  navbar:
    # background: primary
    left:
      - text: Schedule
        file: pages/schedule.qmd
      - text: Book
        file: book/book.qmd

  sidebar:
    - title: "Book"
      style: "docked"
      logo: images/Logo.png
      contents:
        - book/book.qmd
        - section: "Unit 1: Design and Electronics"
          contents:
            - book/01-IntroductionAndDesign.qmd
            - book/02-LayoutAndPrototyping.qmd
            - book/03-SafetyAndElectronics.qmd
            - book/04-ProgrammingWithToit.qmd
        - text: "---"
        - section: "Unit 2: Modeling and Feedback Control"
          contents:
        - text: "---"
        - section: "Unit 3: Maps and Motion Planning"
          contents:
        - text: "---"
        - section: "Unit 4: Uncertainty and State Estimation"
          contents:
        - text: "---"
        - section: "Unit 5: Localization and Mapping"
          contents:
        - text: "---"
        - section: "Unit 6: Vision and Learning"
          contents:
        - text: "---"
        - section: "Unit 7: Societal Impacts"
          contents:
        - text: "---"
        - section: "Back Matter"
          contents:
            - book/Glossary.qmd
            - book/Projects.qmd
            - book/A1-Notation.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
