---
title: "Robots in Our Society"
---

## What you will learn

- How to write a case study
- How to analyze a case study

## Terminology

case study
: An instance of some event (real or hypothetical) analyzed to better understand a issue or principle

## Lecture

This lecture will take place in class.

## Exercise

For this exercise, you will write a case study and share it with your classmates.

You will submit your responses on gradescope. **Only one partner should submit.** The submitter will add the other partner through the gradescope interface.

Additional details for using gradescope can be found here:

- [Submitting an Assignment](https://help.gradescope.com/article/ccbpppziu9-student-submit-work)
- [Adding Group Members](https://help.gradescope.com/article/m5qz2xsnjy-student-add-group-members)
- [gradescope Student Help Center](https://help.gradescope.com/category/cyk4ij2dwi-student-workflow)

You should open the gradescope assignment now so that you know what to work complete.

### Grading

I will grade all exercises using a scale of "Nailed It" / "Not Yet". See the course [grading policy](../index.qmd#grading) for more information, and check gradescope for deadlines.

### Overview

How many of you have read and analyzed a "case study"?

I could not find any that I liked enough to use for this course, so instead we're going to write some case studies together, and then share them with one another.

Specifically, you all will:

1. Form groups of three (can be different)
2. Select a case study topic.
3. Outline your case study.
4. Write your case study.
5. Write discussion questions for your case study.

### Before You Start

You should first scan this [template for technology ethics case studies](https://www.scu.edu/ethics/focus-areas/technology-ethics/a-template-for-technology-ethics-case-studies/). You do not need to memorize or start writing just yet, but it will put you in the right frame of mind.

You can also read through some of the case studies from the [Princeton Dialogues on AI and Ethics](https://aiethics.princeton.edu/case-studies/case-study-pdfs/). The case studies that you write will not be as long or detailed as these, but they will be similar in structure.

### Case Study Topics

First, decide on your groups topic.

- Surveillance and privacy
- Manipulation
- Opacity and bias
- Human-Robot interaction
- Automation and employment
- Weaponization
- Singularity
- Income inequality

### Outline Your Case Study

Each case study will eventually include the following sections:

- Background (1-3 paragraphs)
- Scenario (1-3 paragraphs)
- Ethical issues (2-5 issues)
- Discussion issues (3-5 questions)
- (Optional) Acknowledgements
- (Optional) References

But before you begin, you should outline your case study by considering the following questions:

- *When* did the case take place?
- *Where* did the case take place?
- *What* are the relevant facts of the case?
- *Who* are the relevant participants?
- *Which* details and ethical principles are relevant to the case?
- *How* did the case unfold?
- *Why* did the participants act as they did?

You can refer back to the [template for technology ethics case studies](https://www.scu.edu/ethics/focus-areas/technology-ethics/a-template-for-technology-ethics-case-studies/) for more detailed versions of these questions.

### Use of AI

If you use AI-based tools such as ChatGPT or Copilot for writing or writing assistance, you must disclose that use as follows:

- If you include verbatim text generated by an AI-based tool, it should be cited using quotation marks, where the citation should include the prompt used as input to generate the quoted text. For example, "ChatGPT4. Prompt: "What is differential privacy?", August 27, 2024."
- If you include significantly paraphrased text that was initially generated by ann AI-based tool, then it should be cited without quotation marks, where the citation should include the prompt used (as shown above).
- If you use AI-based tools to revise writing style (e.g., change the text to active voice) or fix typographical issues, then you should mention in the acknowledgements section which sections were revised using what kind of instructions or prompts. For example, "We used ChatGPT4 to revise the text in Section 4 to correct any typos, grammatical errors, and awkward phrasing."

### Write Your Case Study

Fill in the sections of your case study.

- Background (1-3 paragraphs)
- Scenario (1-3 paragraphs)
- Ethical issues (2-5 issues)
- Discussion issues (3-5 questions)
- (Optional) Acknowledgements
- (Optional) References

For the ethical issues and discussion question, you might find the following resources useful.

#### Common AI Ethics Issues

- Questions on oversight and accountability
    - Which laws and regulations might be applicable to this project?
    - How is ethical accountability being achieved?

- Questions on data privacy and anonymity
    - How might the legal rights of organizations and individuals be impinged by our use of the data?
    - How might individuals’ privacy and anonymity be impinged via aggregation and linking of the data?

- Questions on data availability and validity
    - How do you know that the data is ethically available for its intended use?
    - How do you know that the data is valid for its intended use?

- Questions on model bias
    - How have we identified and minimized any bias in the data or in the model?
    - How was any potential modeler bias identified and then, if appropriate, mitigated?

- Questions on model transparency and interpretation
    - How transparent does the model need to be and how is that transparency achieved?
    - What are likely misinterpretations of the results and what can be done to prevent those misinterpretations?

These questions are from [Integrating Ethics within Machine Learning Courses](https://dl.acm.org/doi/10.1145/3341164) by J. Saltz et al.

#### Ethical Sweeps

You may also find the following these "ethical sweep" guidelines useful.

**General Questions:**

- Should we even be doing this?
- What might be the accuracy of a simple non-ML alternative?
- What processes will we use to handle appeals/mistakes?
- How diverse is our team?

**Data Questions:**

- Is our data valid for its intended use?
- What bias could be in our data? (All data contains bias.)
- How could we minimize bias in our data and model?
- How should we "audit" our code and data?

**Impact Questions:**

- Do we expect different errors rates for different sub-groups in the data?
- What are likely misinterpretations of the results and what can be done to prevent those misinterpretations?
- How might we impinge individuals' privacy and/or anonymity?

## Wrap-Up

The exercise for this chapter focused on the ethics of robotics and automation. I also want to encourage your to think about the history of robotics and how they are depicted in popular culture. These are topics that we will visit later in the course.

## Resources

- [Princeton Dialogues on AI and Ethics](https://aiethics.princeton.edu/case-studies/case-study-pdfs/)
