---
title: "Notation"
format: html
---


This page will fill-in as the semester progresses.

<!-- what’s in a row, column , do they sum etc
 -->

<!-- Mathematical notation
- linear algebra
- calculus
- probability -->

<!-- dimensional analysis
syntax checking (possible to multiple?)
semantic checking (make sense to perform inverse?) -->

## Acronyms and Initialisms

- AGV (autonomous ground vehicle)
- AMR (autonomous mobile robot)
- DOF (degrees of freedom)
- EKF (extended Kalman filter)
- FBD (free body diagram)
- IMU (inertial measurement unit)
- LIDAR (light detection and ranging)
- LQR (linear quadratic regulator)
- MPC (model predictive control)
- ODE (ordinary differential equation)
- PID (proportional integral derivative)
- ROS (robot operating system)
- SLAM (simultaneous localization and mapping)
- UGV (unmanned ground vehicle)
- WMR (wheeled mobile robot)

## Related Terms

- motion planning (specifying the motion needed to follow a path)
- path planning (finding a path)
- path, route (sequence of points)
- trajectory (path parameterized by time)

## Notation



<!-- [Notation](https://dynref.engr.illinois.edu/rvn.html)
[Tips for mathematical handwriting](https://johnkerl.org/doc/ortho/ortho.html)
[Householder notation](https://www.cs.utexas.edu/users/flame/laff/alaff/a1appendix-householder-notation.html) -->

<!-- - values
	+ scalar
	+ vector
	+ matrix
	+ components
- unit vectors
- estimates
- frames
- basis
- transformations
- time derivative, other derivatives -->

<!-- options
- dot
- bar
- hat
- bold
- italics
- arrow
- upper/lower case
- underline
- script/mathcal/blackboard
- Greek -->


| Symbol                                                                                             | Description                                                |
| ---                                                                                                | ---                                                        |
| $\{A\}$, $\{G\}$, $\{R\}$                                                                          | Reference frames                                           |
| $\{B\} \rightarrow \{{}^A_B R, {}^A P\}$                                                           | Relative frame (frame $\{B\}$ defined relative to $\{A\}$) |
| ${}^A P = [P_x, P_y]^T$                                                                            | Point in a frame (upper case letters)                      |
| ${}^A v = [v_x, v_y]^T$                                                                            | Vector in a frame (lower case letters)                     |
| ${}^A_B R = \begin{bmatrix} \cos \theta & -\sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}$ | Rotation matrix                                            |
| ${}^A Q = {}^A_B R {}^A Q + {}^A P$                                                                | Transformation/change in reference                         |
| $q$                                                                                                | Generalized coordinates (state or configuration)           |
| $\dot q$                                                                                           | Generalized velocities (update equation)                   |
