---
title: "Troubleshooting"
format: html
---

Please let me know when you run into issues. I will update this page with solutions as we find them.

## No serial data received

If you see an output like the following:

```text
Connecting......................................

A fatal error occurred: Failed to connect to ESP32: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
Error: exit status 1
```

It likely means `jag` is trying to use the wrong port. Try listing the available ports with the following command:

```bash
jag port --list
```

And add the correct port to whatever command you are trying to run. For example:

```bash
jag flash --chip esp32s3 --port /dev/cu.usbmodem14401
```

## `npm` cannot install `wscat`

If you see an error message like the following:

```bash
> npm install -g wscat

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/wscat
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir ‘/usr/local/lib/node_modules/wscat’
npm ERR! [Error: EACCES: permission denied, mkdir ‘/usr/local/lib/node_modules/wscat’] {
npm ERR!  errno: -13,
npm ERR!  code: ‘EACCES’,
npm ERR!  syscall: ‘mkdir’,
npm ERR!  path: ‘/usr/local/lib/node_modules/wscat’
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in: /Users/ACCOUNT/.npm/_logs/2024-09-12T17_07_20_354Z-debug-0.log
```

You will need to either

- changes the permissions of your `/usr/local/lib/node_modules` directory, or
- install `wscat` with `sudo`: `sudo npm install -g wscat`

## `WARN: connect failed`

You might often see an error message like the following:

```text
[toit] INFO: running on ESP32S3 - revision 0.2
[wifi] DEBUG: connecting
[wifi] WARN: connect failed {reason: timeout}
[wifi] DEBUG: closing
[jaguar] WARN: running Jaguar failed due to ‘DEADLINE_EXCEEDED’ (1/3)
[wifi] DEBUG: connecting
[wifi] WARN: connect failed {reason: unknown reason (39)}
[wifi] DEBUG: closing
[jaguar] WARN: running Jaguar failed due to ‘CONNECT_FAILED: unknown reason (39)’ (2/3)
[wifi] DEBUG: connecting
[wifi] WARN: connect failed {reason: unknown reason (39)}
[wifi] DEBUG: closing
[jaguar] WARN: running Jaguar failed due to ‘CONNECT_FAILED: unknown reason (39)’ (3/3)
[jaguar] INFO: backing off for 5s
```

The first thing you should try is to move your antenna away from other wires and electrical components (e.g., the motors and battery). If that does not work, then try connecting to the TP-Link router instead of Claremont-ETC or PomonaIoT.

## PSRAM Initialization Error

You can ignore the following error message:

```text
E (299) quad_psram: PSRAM ID read error: 0x00ffffff, PSRAM chip not found or not supported, or wrong PSRAM line mode
E (299) esp_psram: PSRAM enabled but initialization failed. Bailing out.
```
